---
version: '3'

services:
  pp-code-metrics:
    container_name: pp-code-metrics
    hostname: pp-code-metrics
    image: neofob/pp-code-metrics:latest
    restart: always
    volumes:
      - ./my_settings.yml:/opt/pp-code-metrics/my_settings.yml
